### ISSUE TITLE
Ignore Gemfile.lock

### ISSUE THREAD

**Issue by nicolas-brousse** [komposable/dekorator#21]

**Comment by TCsTheMechanic** [comment]
Can I take this one ?

**Comment by nicolas-brousse** [comment]
Sure

**Comment by TCsTheMechanic** [comment]
I'm trying to push to a new branch but this error is happening.
remote: Permission to komposable/dekorator.git denied to TCsTheMechanic.
fatal: unable to access 'https://github.com/komposable/dekorator.git/': The requested URL returned error: 403

**Comment by Spone** [comment]
@TCsTheMechanic you should fork the project and push to a branch on your fork, then open a PR from your fork to this repository: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by TCsTheMechanic** [comment]
I did it:
git checkout -b ignored_gemfile_lock
(did some changes)
git add *
git commit -m "Ignored Gemfile.lock"
git push origin ignored_gemfile_lock
but with the last command it says that I dont have permission...

**Comment by Spone** [comment]
Can you run `git remote -v` and tell me the result?

**Comment by TCsTheMechanic** [comment]
origin  https://github.com/komposable/dekorator.git (fetch)
origin  https://github.com/komposable/dekorator.git (push)

**Comment by Spone** [comment]
Yes, so the problem is that you cloned this repository directly, instead of forking it first.
You do not have rights to this repository so you cannot push to it.

Please read this documentation and fork the repository first: https://help.github.com/en/github/getting-started-with-github/fork-a-repo

Then do your changes on the fork.

Then you will be able to push your changes to your fork.

Then you can open a PR.

**Comment by Spone** [comment]
@TCsTheMechanic I see that you managed to create #22 
great :+1: 
thanks for your contribution

**Comment by TCsTheMechanic** [comment]
@Spone Thak you for your help :D

**Comment by nicolas-brousse** [comment]
Closed by #22
